### ISSUE TITLE
Error in rule wide_fdr_peaks

### ISSUE THREAD

**Issue by StephanieBohaczuk** [fiberseq/fiberseq-fire#2]
I'm getting  "Error in rule wide_fdr_peaks" regardless of whether I use the new "min_per_acc_peak".

My input data is phased reads mapping to a ~200 kb region of chromosome 19.

I sent you more details on slack. Let me know if I can help with the troubleshooting.

**Comment by mrvollger** [comment]
Fixed by #3!
