### ISSUE TITLE
modwt required but not mentioned in README

### ISSUE THREAD

**Issue by MorganHamm** [fiberseq/fiberseq-fire#4]
I freshly cloned fiberseq-fire on Nov. 2nd 2023, and attempted to run the pipeline. I got the following error:
`Error: modwt not found in PATH, but it is required for FIRE.`

Workaround:
I added modwt file to my path, and the error did not appear when I tried again to run the pipeline.

Suggestion:
Either direct users to add this file to their path in the README.md, including where they can get this file, OR incorporate modwt in the conda environment that it's used in.

**Comment by sjneph** [comment]
I think that modwt has been removed from the latest upgrade to fiberseq-fire.
